### ISSUE TITLE
Permission to use in Roam42

### ISSUE THREAD

**Issue by TfTHacker** [mgsloan/roam-navigator#1]
Hi,
Your tool here is brilliant. Thank you for your work on it. I have had a few requests to add it to Roam42 and I have to admit I would like it. But I like to get permission before doing that. Respect the author.

Would you be ok with that? if not, then I will just keep referring people to your addin. but I can't use your addin at work due to browser lockdown. So adding to roam42 woiuld solve the issue.

You could even submit it as a feature to Roam42 if you are so inclined :-) github.com/roamhacker/roam42

**Comment by mgsloan** [comment]
Thanks, I'm glad you like it!

Sure feel free!  I'm happy to get roam-navigator in more hands.  Especially
if it is still easy to get enhancements to it out to users.

I haven't quite gotten around to figuring out how to add it, but could
certainly open a PR if it is a straightforward process

**Comment by TfTHacker** [comment]
Thank you. If you don't mind I will integrate it, since I need to integrate it with some conflicts on the Roam42 side I have it mostly working (small mods). just have to say its brilliant code! I don't know if you have seen roam42, its basically for those not using browser extensions. But many still prefer this, so I will be sending them your way :-)

If I find any issues, will send feedback back to you or PR.

Great work! great service to community.
