### ISSUE TITLE
Updates for roam

### ISSUE THREAD

**Issue by TfTHacker** [mgsloan/roam-navigator#10]
Hi Mike,
I am not setup right now to do a PR, but thought I would mention some fixes I made to make navigator code work in Roam currently:

renderTipInternal flex-h-box is no longer valid. changed to findParent(el, matchingClass('**rm-block-main**')).prepend(tip);

Warm greetings

**Comment by mgsloan** [comment]
Thanks for letting me know the fix!  I also saw this breakage in my offline roam yesterday, but hadn't gotten around to looking into it.  Fix released in version 9.

I highly recommend https://hub.github.com/ for easily creating forks and PRs
