### ISSUE TITLE
CSS change for breadcrumbs

### ISSUE THREAD

**Issue by TfTHacker** [mgsloan/roam-navigator#11]
Mike, looks Roam changed CSS today and the breadcrumbs on top stopped showing. I changed this line:

      const topbar = selectUnique(document, '.roam-topbar > .flex-h-box');

to

      const topbar = selectUnique(document, '.roam-topbar > .rm-files-dropzone >  .flex-h-box');

in renderBreadcrumbs() and that seemed to resolve it. As you know, I can't push up a fix. So I post it here.

**Comment by mgsloan** [comment]
Thanks!  Fixed in 60028719d4f0db2720f5b3f0ebb9b95d03be5cbf
