### ISSUE TITLE
Aliased page references not getting keys assigned for navigator

### ISSUE THREAD

**Issue by TfTHacker** [mgsloan/roam-navigator#3]
This is low priority, but wanted to report. If I have the following page reference that Navigator assigns a shortcut too:

[[Test]]

and then an Alias to the same page, as in the following example:

[This is an alias to Test]([[Test]])

The alias does not get assigned a shortcut.

Again, low priority.

P.S. I have already integrated navigator into Roam42 and have it being tested. Getting great feedback. Combined with some of Roam42's shortcuts, its a killer combo.

**Comment by mgsloan** [comment]
Thanks for reporting!  I've noted it down in my list of future enhancements.

**Comment by mgsloan** [comment]
Fixed in version 6!
