### ISSUE TITLE
Filters in sidebar are getting cropped

### ISSUE THREAD

**Issue by TfTHacker** [mgsloan/roam-navigator#7]
Hi Mike, Found a small issue. If the filter button is clicked in the sidebar, the filter that appears gets cropped. I am including an image of the cropping.
![Screenshot 2020-10-09 at 20 58 06](https://user-images.githubusercontent.com/69121180/95621672-61e6d780-0a72-11eb-80b3-153a9370a97a.png)

thanks for your amazing work on roam-navigator.

**Comment by mgsloan** [comment]
Looks like changes in Roam's DOM has fixed this without any roam-navigator changes!
