### ISSUE TITLE
Toggling checkboxes

### ISSUE THREAD

**Issue by TfTHacker** [mgsloan/roam-navigator#8]
The Roam42 community loves your work here. Just another note of thanks. It fits in well with many tools we are using.

Enhancement request: could navigator provide shortcuts for toggling checkboxes on and off?

Warm regards

**Comment by mgsloan** [comment]
Could do, but it's low priority because you can also just put the cursor on the block and use ctrl-enter.  Leaning towards not supporting it, since the tips add clutter and use up potential key combinations.
